#!/usr/bin/env python3
"""
build.py — TinyFramework packaging & build script.

Pipeline:
  1. gather frontend bundle (JS / assets) from --in
  2. (optional) compile JS to QuickJS bytecode via `qjsc` (--bytecode)
  3. encrypt with ChaCha20-Poly1305 (RFC 8439)  ->  bundle = nonce|ct|tag
     (produces a bundle that mini_vfs_decrypt.c decrypts in RAM, verbatim;
      the RFC-8439 vectors prove C <-> cryptography interop)
  4. emit encrypted_assets.h  (C array + key)
  5. invoke the C compiler (gcc/clang/cl) + UPX strip

The cipher in build.py uses `cryptography` (pip install cryptography).
The bundle layout matches mini_vfs_decrypt.c:  [12-byte nonce][N-byte
ciphertext][16-byte tag]. AAD is empty (the loader passes aad=NULL, len=0).
Bytecode payloads are prefixed with b"QJC1" so the loader routes them to
JS_ReadObject instead of JS_Eval.
"""
import os, sys, subprocess, argparse, shutil

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in",  dest="src",  required=True, help="JS bundle file/dir to package")
    ap.add_argument("--out", dest="outh", default="encrypted_assets.h")
    ap.add_argument("--key", default=None, help="32-byte hex key (default: random)")
    ap.add_argument("--bytecode", action="store_true", help="compile JS via qjsc first")
    ap.add_argument("--cc",  default=None, help="compiler (gcc/clang/cl) default: autodetect")
    ap.add_argument("--upx", action="store_true", help="UPX-compress the final binary")
    ap.add_argument("--exe", default="tiny_app")
    ap.add_argument("--no-compile", action="store_true", help="emit assets header only")
    ap.add_argument("--jit", action="store_true",
                    help="build QuickJS from source with the baseline JIT (JS_JIT)")
    ap.add_argument("--jit-codegen", action="store_true",
                    help="with --jit, also enable SLJIT native codegen (JS_JIT_CODEGEN)")
    a = ap.parse_args()

    from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
    import secrets

    # 1) gather payload
    if os.path.isdir(a.src):
        parts = []
        for root, _, files in os.walk(a.src):
            for f in sorted(files):
                if f.endswith((".js", ".mjs")):
                    parts.append(f"-- {f} --\n")
                    with open(os.path.join(root, f), "rb") as fh: parts.append(fh.read())
        payload = b"".join(p if isinstance(p, bytes) else p.encode() for p in parts)
    else:
        with open(a.src, "rb") as fh: payload = fh.read()
    print(f"[build] payload: {len(payload)} bytes")

    # 2) optional bytecode
    if a.bytecode:
        qjsc = shutil.which("qjsc")
        if not qjsc:
            print("[build] --bytecode given but qjsc not found; using source")
        else:
            tmp_js  = "_build_bundle.js"
            tmp_qjc = "_build_bundle.qjc"
            with open(tmp_js, "wb") as fh: fh.write(payload)
            subprocess.check_call([qjsc, "-e", "-o", tmp_qjc, tmp_js])
            with open(tmp_qjc, "rb") as fh: payload = fh.read()
            payload = b"QJC1" + payload      # marker the loader checks
            os.remove(tmp_js); os.remove(tmp_qjc)
            print(f"[build] bytecode payload: {len(payload)} bytes (incl. QJC1 marker)")

    # 3) encrypt
    key = bytes.fromhex(a.key) if a.key else secrets.token_bytes(32)
    assert len(key) == 32, "key must be 32 bytes"
    nonce = secrets.token_bytes(12)
    ct_tag = ChaCha20Poly1305(key).encrypt(nonce, payload, None)  # None == empty AAD
    bundle = nonce + ct_tag                       # nonce(12) | ct(N) | tag(16)
    print(f"[build] bundle: {len(bundle)} bytes  (nonce+ct+tag)")

    # 4) emit C header
    def hex_array(b, per=12):
        lines = []
        for i in range(0, len(b), per):
            chunk = b[i:i+per]
            lines.append("    " + ",".join(f"0x{x:02x}" for x in chunk) + ",")
        return "\n".join(lines)
    with open(a.outh, "w") as fh:
        fh.write("/* AUTO-GENERATED by build.py — do not edit. */\n")
        fh.write("#pragma once\n#include <stdint.h>\n#include <stddef.h>\n\n")
        fh.write(f"static const uint8_t MINI_BUNDLE[{len(bundle)}] = {{\n{hex_array(bundle)}}};\n")
        fh.write(f"static const size_t  MINI_BUNDLE_SIZE = {len(bundle)};\n")
        fh.write(f"static const uint8_t MINI_KEY[32] = {{\n{hex_array(key)}}};\n")
    print(f"[build] wrote {a.outh}")

    if a.no_compile:
        return

    # 5a) pick compiler (also needed by the JIT build step below)
    cc = a.cc or next((c for c in ("gcc","clang","cl") if shutil.which(c)), None)
    if not cc:
        print("[build] no compiler found; assets header emitted, skipping link")
        return

    # 4.5) optional: build QuickJS from source with the baseline JIT
    qjs_lib = None
    extra_cflags = []
    if a.jit:
        qjs_dir = "libs/quickjs"
        build_dir = os.path.join(qjs_dir, "build")
        cmake_cfg = ["cmake", "-S", qjs_dir, "-B", build_dir, "-DJS_JIT=ON"]
        if a.jit_codegen:
            cmake_cfg.append("-DJS_JIT_CODEGEN=ON")
        print("[build] " + " ".join(cmake_cfg))
        subprocess.check_call(cmake_cfg)
        subprocess.check_call(["cmake", "--build", build_dir, "--target", "qjs"])
        is_msvc = (cc == "cl")
        qjs_lib = os.path.join(build_dir,
                              "qjs.lib" if is_msvc else "libqjs.a")
        D = "/D" if is_msvc else "-D"
        I = "/I" if is_msvc else "-I"
        extra_cflags = [D + "JS_JIT"]
        if a.jit_codegen:
            extra_cflags += [D + "JS_JIT_CODEGEN", I + "libs/sljit/sljit_src"]

    # 5b) compile the app
    cflags = "-std=c99 -DENABLE_CUSTOM_MINI_ENGINE -Os -flto -ffunction-sections -fdata-sections".split()
    ldflags = ["-Wl,--gc-sections", "-lglfw", "-lGL", "-lm"]
    if cc == "cl":
        cflags = ["/std:c11", "/DENABLE_CUSTOM_MINI_ENGINE", "/O2", "/GL", "/Gy"]
        ldflags = ["glfw3.lib", "opengl32.lib", "user32.lib", "gdi32.lib"]
    srcs = ["src/main.c","src/mini_renderer.c","src/mini_dom.c","src/mini_html5.c",
            "src/mini_css.c","src/mini_bidi.c","src/mini_shaping.c","src/mini_eventloop.c",
            "src/mini_js_bridge.c","src/mini_vfs_decrypt.c",
            "src/mini_cdp_server.c","src/mini_cdp_domains.c","src/mini_png.c",
            "src/mini_net.c","src/mini_events.c","src/mini_gradient.c","src/mini_diag.c"]
    if a.jit:
        cflags += extra_cflags + [("/I" if cc == "cl" else "-I") + "libs/quickjs"]
        ldflags.append(qjs_lib)
    else:
        ldflags.append("quickjs.lib" if cc == "cl" else "-lquickjs")
    cmd = [cc, *cflags, "-Iinclude", *srcs, "-o", a.exe, *ldflags]
    print("[build] " + " ".join(cmd))
    subprocess.check_call(cmd)

    # strip + UPX
    if cc != "cl" and shutil.which("strip"):
        subprocess.call(["strip", "-s", a.exe])
    if a.upx and shutil.which("upx"):
        subprocess.check_call(["upx", "--ultra-brute", "-q", a.exe])
    print(f"[build] -> {a.exe}")

if __name__ == "__main__":
    main()
