/*
 * mini_devtools.c — in-engine DevTools overlay (JS bundle + install/toggle).
 *
 * See mini_devtools.h for the design rationale. The whole panel UI lives in
 * DEVTOOLS_JS below; it is eval'd once into the bridge context and exposes
 * window.__miniDT {toggle, open, close, isOpen}. F12 -> mini_devtools_toggle.
 */
#include "mini_devtools.h"
#include "mini_js_bridge.h"
#include <stdio.h>
#include <string.h>

/* The DevTools bundle. Built from the engine's own DOM/JS so it renders
   natively and reads live data (DOM tree, console log ring, page-global eval)
   without a network round-trip. Style is a faithful Chrome-DevTools dark
   approximation, not a byte-identical clone.                          */
static const char *DEVTOOLS_JS =
    "(function(){\n"
    "  if (window.__miniDT) return;\n"
    "  var D = null, tabs = {}, curTab = 'elements', logSince = 0, pollTimer = null;\n"
    "  var lastHL = null, _open = false;\n"
    "  function el(tag, cls, txt){ var e=document.createElement(tag); if(cls) e.className=cls; if(txt!=null) e.textContent=txt; return e; }\n"
    "  function css(e,s){ for(var k in s) { var p=k.replace(/([A-Z])/g,'-$1').toLowerCase(); if(e.style&&e.style.setProperty) e.style.setProperty(p, s[k]); } return e; }\n"
    "  function esc(s){ return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }\n"
    "  function build(){\n"
    "    D = el('div'); D.id='__miniDT';\n"
    "    css(D, {position:'fixed',left:'0px',right:'0px',bottom:'0px',height:'380px',zIndex:'99999',\n"
    "      display:'none',flexDirection:'column',background:'#242424',color:'#e8eaed',\n"
    "      fontFamily:'\"Cascadia Code\", Consolas, Menlo, monospace',fontSize:'12px',lineHeight:'1.5',\n"
    "      borderTop:'1px solid #3c4043',boxShadow:'0 -4px 16px rgba(0,0,0,0.6)'});\n"
    "    \n"
    "    var bar = css(el('div'), {display:'flex',alignItems:'center',background:'#202124',\n"
    "      borderBottom:'1px solid #3c4043',padding:'0 4px',height:'32px',flex:'0 0 auto'});\n"
    "    function tab(id,label){ \n"
    "      var t=el('div','',label); \n"
    "      css(t,{padding:'0 16px',cursor:'pointer',lineHeight:'30px',color:'#9aa0a6',borderBottom:'2px solid transparent',fontSize:'13px'});\n"
    "      t.addEventListener('mouseenter', function(){ if(curTab!==id) t.style.color='#e8eaed'; });\n"
    "      t.addEventListener('mouseleave', function(){ if(curTab!==id) t.style.color='#9aa0a6'; });\n"
    "      t.addEventListener('click', function(){ curTab=id; showTab(); });\n"
    "      tabs[id]=t; bar.appendChild(t); \n"
    "    }\n"
    "    tab('elements','Elements'); tab('console','Console'); tab('network','Network');\n"
    "    var spacer = css(el('div'), {flex:'1'}); bar.appendChild(spacer);\n"
    "    var refresh = css(el('div','','↻'), {padding:'0 12px',cursor:'pointer',color:'#9aa0a6',lineHeight:'32px',fontSize:'15px'});\n"
    "    refresh.addEventListener('mouseenter', function(){ refresh.style.color='#e8eaed'; });\n"
    "    refresh.addEventListener('mouseleave', function(){ refresh.style.color='#9aa0a6'; });\n"
    "    refresh.addEventListener('click', function(){ showTab(); }); bar.appendChild(refresh);\n"
    "    var closeBtn = css(el('div','','✕'), {padding:'0 14px',cursor:'pointer',color:'#9aa0a6',lineHeight:'32px',fontSize:'15px'});\n"
    "    closeBtn.addEventListener('mouseenter', function(){ closeBtn.style.color='#e8eaed'; });\n"
    "    closeBtn.addEventListener('mouseleave', function(){ closeBtn.style.color='#9aa0a6'; });\n"
    "    closeBtn.addEventListener('click', function(){ window.__miniDT.close(); }); bar.appendChild(closeBtn);\n"
    "    D.appendChild(bar);\n"
    "    \n"
    "    var body = css(el('div'), {flex:'1 1 auto',display:'flex',width:'100%',height:'100%',overflow:'hidden'});\n"
    "    D.appendChild(body);\n"
    "    \n"
    "    var ePane = css(el('div'), {flex:'1',display:'flex',width:'100%',height:'100%',overflow:'hidden'});\n"
    "    var domTree = css(el('div'), {flex:'0 0 65%',width:'65%',height:'100%',overflow:'auto',borderRight:'1px solid #3c4043',padding:'6px 0'});\n"
    "    var stylesPane = css(el('div'), {flex:'1',width:'35%',height:'100%',overflow:'auto',background:'#242424'});\n"
    "    ePane.appendChild(domTree); ePane.appendChild(stylesPane);\n"
    "    D.__ePane=ePane; D.__domTree=domTree; D.__stylesPane=stylesPane;\n"
    "    body.appendChild(ePane);\n"
    "    \n"
    "    var cPane = css(el('div'), {flex:'1',display:'none',flexDirection:'column',width:'100%',height:'100%'});\n"
    "    var cToolbar = css(el('div'), {display:'flex',alignItems:'center',padding:'0 12px',height:'28px',borderBottom:'1px solid #3c4043',background:'#242424',color:'#9aa0a6'});\n"
    "    var cClear = css(el('div','','⊘ Clear'), {cursor:'pointer'});\n"
    "    cClear.addEventListener('mouseenter', function(){ cClear.style.color='#e8eaed'; });\n"
    "    cClear.addEventListener('mouseleave', function(){ cClear.style.color='#9aa0a6'; });\n"
    "    cClear.addEventListener('click', function(){ D.__cLog.innerHTML=''; });\n"
    "    cToolbar.appendChild(cClear);\n"
    "    var cLog = css(el('div'), {flex:'1',width:'100%',height:'100%',overflow:'auto',padding:'4px 0'});\n"
    "    var cInputRow = css(el('div'), {display:'flex',alignItems:'center',borderTop:'1px solid #3c4043',padding:'6px 12px'});\n"
    "    var cPrompt = css(el('span'), {color:'#8ab4f8',marginRight:'12px',fontWeight:'bold'}); cPrompt.textContent='>';\n"
    "    var cInput = el('input'); cInput.type='text';\n"
    "    css(cInput,{flex:'1',background:'transparent',border:'none',color:'#e8eaed',outline:'none',fontFamily:'inherit',fontSize:'inherit'});\n"
    "    cInputRow.appendChild(cPrompt); cInputRow.appendChild(cInput);\n"
    "    cPane.appendChild(cToolbar); cPane.appendChild(cLog); cPane.appendChild(cInputRow);\n"
    "    D.__cPane=cPane; D.__cLog=cLog;\n"
    "    body.appendChild(cPane);\n"
    "    \n"
    "    cInput.addEventListener('keydown',function(e){\n"
    "      if(e.key==='Enter' || e.keyCode===13 || e.keyCode===257){\n"
    "        var ex = cInput.value; if(!ex) return; cInput.value='';\n"
    "        var ln = css(el('div'), {padding:'4px 16px',borderBottom:'1px solid #3c4043',color:'#8ab4f8'}); ln.textContent='> '+ex; cLog.appendChild(ln);\n"
    "        var res=''; \n"
    "        try{ \n"
    "          var r = window.eval(ex); \n"
    "          if(typeof r==='undefined') res='undefined';\n"
    "          else if(r===null) res='null';\n"
    "          else if(typeof r==='function') res='[Function]';\n"
    "          else if(typeof r==='object') { try{ res=JSON.stringify(r); }catch(e2){ res=String(r); } }\n"
    "          else res = String(r); \n"
    "        } catch(err){ \n"
    "          var errRow = css(el('div'), {padding:'4px 16px',color:'#ff8080',background:'#290000',borderBottom:'1px solid #3c4043'});\n"
    "          errRow.textContent=String(err); cLog.appendChild(errRow);\n"
    "          if(cLog.lastChild && cLog.lastChild.scrollIntoView) cLog.lastChild.scrollIntoView();\n"
    "          return;\n"
    "        }\n"
    "        var ro = css(el('div'), {padding:'4px 16px',color:'#e8eaed',borderBottom:'1px solid #3c4043'});\n"
    "        ro.textContent='< '+res; cLog.appendChild(ro); \n"
    "        if(cLog.lastChild && cLog.lastChild.scrollIntoView) cLog.lastChild.scrollIntoView();\n"
    "      }\n"
    "    });\n"
    "    document.body.appendChild(D);\n"
    "  }\n"
    "  \n"
    "  function showTab(){\n"
    "    for(var k in tabs) css(tabs[k], {color:k===curTab?'#8ab4f8':'#9aa0a6',borderBottom:k===curTab?'2px solid #8ab4f8':'2px solid transparent'});\n"
    "    css(D.__ePane, {display:curTab==='elements'?'flex':'none'});\n"
    "    css(D.__cPane, {display:curTab==='console'?'flex':'none'});\n"
    "    if(curTab==='elements') { D.__domTree.innerHTML=''; renderNode(document.body, 0, D.__domTree); }\n"
    "    if(curTab==='console') flushLogs();\n"
    "  }\n"
    "  \n"
    "  function inspect(node){\n"
    "    if(lastHL && lastHL.style) lastHL.style.outline=''; if(!node||!node.style) return;\n"
    "    lastHL=node; node.style.outline='2px solid #8ab4f8';\n"
    "    var sp=D.__stylesPane; sp.innerHTML='';\n"
    "    var h=css(el('div'), {padding:'6px 12px',borderBottom:'1px solid #3c4043',background:'#2f3136',color:'#e8eaed',fontWeight:'bold'});\n"
    "    h.textContent='Styles Computed'; sp.appendChild(h);\n"
    "    var cs = (typeof getComputedStyle==='function')?getComputedStyle(node):{};\n"
    "    var keys=['display','flex-direction','justify-content','align-items','width','height','color','background-color','font-size','margin','padding','border','position','z-index'];\n"
    "    for(var i=0;i<keys.length;i++){\n"
    "      var row = css(el('div'), {display:'flex',padding:'4px 12px'});\n"
    "      var k = css(el('span'), {color:'#9cdcfe',width:'140px',flexShrink:'0'}); k.textContent=keys[i];\n"
    "      var v = css(el('span'), {color:'#ce9178',flex:'1',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'});\n"
    "      v.textContent=(cs.getPropertyValue?cs.getPropertyValue(keys[i]):'')||'';\n"
    "      row.appendChild(k); row.appendChild(v); sp.appendChild(row);\n"
    "    }\n"
    "  }\n"
    "  \n"
    "  function renderNode(node, depth, out){\n"
    "    if(!node || node.nodeType!==1) return; if(node.id==='__miniDT' || node.id==='__dt_spacer') return;\n"
    "    var isLeaf = (node.children.length === 0);\n"
    "    var tag = (node.tagName || 'unknown').toLowerCase();\n"
    "    \n"
    "    if(node.__dt_collapsed === undefined){\n"
    "      node.__dt_collapsed = (tag !== 'body' && tag !== 'div' && tag !== 'html');\n"
    "    }\n"
    "    var row = css(el('div'), {paddingLeft:(depth*16 + 16)+'px',whiteSpace:'nowrap',cursor:'pointer',lineHeight:'22px',position:'relative'});\n"
    "    row.addEventListener('mouseenter', function(){ row.style.backgroundColor='#303336'; });\n"
    "    row.addEventListener('mouseleave', function(){ row.style.backgroundColor=''; });\n"
    "    row.addEventListener('click', function(e){ e.stopPropagation(); inspect(node); });\n"
    "    \n"
    "    if(!isLeaf) {\n"
    "      var arr = css(el('span'), {position:'absolute',left:(depth*16+2)+'px',color:'#9aa0a6',fontSize:'10px',width:'14px',textAlign:'center'});\n"
    "      arr.textContent = node.__dt_collapsed ? '▶' : '▼';\n"
    "      arr.addEventListener('click', function(e){\n"
    "        e.stopPropagation();\n"
    "        node.__dt_collapsed = !node.__dt_collapsed;\n"
    "        D.__domTree.innerHTML='';\n"
    "        renderNode(document.body, 0, D.__domTree);\n"
    "      });\n"
    "      row.appendChild(arr);\n"
    "    }\n"
    "    var t='<span style=\"color:#808080\">&lt;</span><span style=\"color:#5db0d7\">'+esc(tag)+'</span>';\n"
    "    var ats=node.attributes||[]; for(var i=0;i<ats.length;i++){ t+=' <span style=\"color:#9cdcfe\">'+esc(ats[i].name)+'</span><span style=\"color:#808080\">=</span><span style=\"color:#ce9178\">&quot;'+esc(ats[i].value)+'&quot;</span>'; }\n"
    "    \n"
    "    if(isLeaf && node.textContent && node.textContent.trim().length>0){\n"
    "      var txt = node.textContent.trim(); if(txt.length>60) txt = txt.substring(0,60)+'...';\n"
    "      t+='<span style=\"color:#808080\">&gt;</span><span style=\"color:#e8eaed\">'+esc(txt)+'</span>';\n"
    "      t+='<span style=\"color:#808080\">&lt;/</span><span style=\"color:#5db0d7\">'+esc(tag)+'</span><span style=\"color:#808080\">&gt;</span>';\n"
    "      var tWrap = document.createElement('span'); tWrap.innerHTML = t; row.appendChild(tWrap); out.appendChild(row);\n"
    "    } else {\n"
    "      if(node.__dt_collapsed && !isLeaf) {\n"
    "        t+='<span style=\"color:#808080\">&gt;</span><span style=\"color:#e8eaed\">...</span><span style=\"color:#808080\">&lt;/</span><span style=\"color:#5db0d7\">'+esc(tag)+'</span><span style=\"color:#808080\">&gt;</span>';\n"
    "        var tWrap = document.createElement('span'); tWrap.innerHTML = t; row.appendChild(tWrap); out.appendChild(row);\n"
    "      } else {\n"
    "        t+='<span style=\"color:#808080\">&gt;</span>';\n"
    "        var tWrap = document.createElement('span'); tWrap.innerHTML = t; row.appendChild(tWrap); out.appendChild(row);\n"
    "        for(var j=0;j<node.children.length;j++) renderNode(node.children[j], depth+1, out);\n"
    "        var closeRow = css(el('div'), {paddingLeft:(depth*16 + 16)+'px',lineHeight:'22px',color:'#808080'});\n"
    "        closeRow.innerHTML='&lt;/<span style=\"color:#5db0d7\">'+esc(tag)+'</span>&gt;';\n"
    "        out.appendChild(closeRow);\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "  \n"
    "  function flushLogs(){\n"
    "    if(!D) return; var log = D.__cLog; log.innerHTML='';\n"
    "    var r=(typeof __mini_log_poll==='function')?__mini_log_poll(0):{entries:[]}; var es=(r&&r.entries)||[];\n"
    "    for(var i=0;i<es.length;i++){\n"
    "      var e=es[i], isErr = (e.level==='error'), isWarn = (e.level==='warning' || e.level==='warn');\n"
    "      var bg = isErr?'#290000':(isWarn?'#332b00':'transparent'), fg = isErr?'#ff8080':(isWarn?'#ffb900':'#e8eaed'), bdr = isErr?'#5c1e1e':(isWarn?'#665500':'#3c4043');\n"
    "      var row=css(el('div'),{whiteSpace:'pre-wrap',wordBreak:'break-all',padding:'6px 16px',backgroundColor:bg,color:fg,borderBottom:'1px solid '+bdr});\n"
    "      if(e.tag) { var ts=css(el('span'),{color:'#9aa0a6',marginRight:'8px'}); ts.textContent='['+e.tag+']'; row.appendChild(ts); }\n"
    "      row.appendChild(document.createTextNode(e.msg||'')); log.appendChild(row);\n"
    "    }\n"
    "    log.scrollTop=log.scrollHeight; logSince=(r&&r.total)||0;\n"
    "  }\n"
    "  \n"
    "  window.__miniDT = {\n"
    "    open:function(){\n"
    "      if(!D) build(); \n"
    "      D.style.display='flex'; _open=true; \n"
    "      var spc = document.getElementById('__dt_spacer');\n"
    "      if(!spc) { spc = css(el('div'),{height:'380px',width:'100%'}); spc.id='__dt_spacer'; document.body.appendChild(spc); }\n"
    "      showTab(); \n"
    "      if(!pollTimer) pollTimer=setInterval(function(){ if(_open && curTab==='console') flushLogs(); },300); \n"
    "    },\n"
    "    close:function(){\n"
    "      _open=false; if(D) D.style.display='none'; \n"
    "      var spc = document.getElementById('__dt_spacer');\n"
    "      if(spc && spc.parentNode) spc.parentNode.removeChild(spc);\n"
    "      if(pollTimer){ clearInterval(pollTimer); pollTimer=null; } \n"
    "      if(lastHL&&lastHL.style) lastHL.style.outline=''; lastHL=null; \n"
    "    },\n"
    "    toggle:function(){ if(!_open) window.__miniDT.open(); else window.__miniDT.close(); },\n"
    "    isOpen:function(){ return _open; },\n"
    "    inspect:function(node){ if(!_open) window.__miniDT.open(); curTab='elements'; showTab(); if(node) inspect(node); }\n"
    "  };\n"
    "  \n"
    "  /* Context Menu (Chrome 风格纯矢量 SVG 现代右键菜单) */\n"
    "  var CM = null;\n"
    "  var itemCut, itemCopy, itemPaste, sepInput, itemSelectAll, itemReload, sepDT, itemInspect;\n"
    "  function closeContextMenu(){\n"
    "    if(CM) CM.style.display='none';\n"
    "  }\n"
    "  function item(svgIcon, text, shortcut, onClick){\n"
    "    var it = css(el('div'), {\n"
    "      display:'flex',alignItems:'center',padding:'7px 12px',margin:'1px 5px',\n"
    "      borderRadius:'6px',cursor:'pointer',boxSizing:'border-box'\n"
    "    });\n"
    "    var ic = css(el('span'), {\n"
    "      width:'16px',height:'16px',display:'flex',alignItems:'center',\n"
    "      justifyContent:'center',marginRight:'10px',flexShrink:'0',\n"
    "      pointerEvents:'none'\n"
    "    });\n"
    "    if(svgIcon) ic.innerHTML = svgIcon;\n"
    "    var tx = css(el('span','',text), {\n"
    "      flex:'1',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',\n"
    "      pointerEvents:'none'\n"
    "    });\n"
    "    it.appendChild(ic); it.appendChild(tx);\n"
    "    if(shortcut){\n"
    "      var sc = css(el('span','',shortcut), {\n"
    "        color:'#9ca3af',fontSize:'11px',marginLeft:'12px',flexShrink:'0',\n"
    "        pointerEvents:'none'\n"
    "      });\n"
    "      it.appendChild(sc);\n"
    "    }\n"
    "    it.addEventListener('mouseenter', function(){ \n"
    "      it.style.backgroundColor='#3b82f6'; \n"
    "      it.style.color='#ffffff'; \n"
    "    });\n"
    "    it.addEventListener('mouseleave', function(){ \n"
    "      it.style.backgroundColor=''; \n"
    "      it.style.color='#f3f4f6'; \n"
    "    });\n"
    "    it.addEventListener('click', function(e){\n"
    "      e.stopPropagation();\n"
    "      closeContextMenu();\n"
    "      if(onClick) onClick();\n"
    "    });\n"
    "    CM.appendChild(it);\n"
    "    return it;\n"
    "  }\n"
    "  \n"
    "  function sep(){\n"
    "    var s = css(el('div'), {height:'1px',background:'rgba(255,255,255,0.08)',margin:'4px 6px'});\n"
    "    CM.appendChild(s);\n"
    "    return s;\n"
    "  }\n"
    "  \n"
    "  function initContextMenu(){\n"
    "    if(CM) return;\n"
    "    CM = el('div'); CM.id='__miniContextMenu';\n"
    "    css(CM, {\n"
    "      position:'fixed',display:'none',zIndex:'100000',width:'180px',\n"
    "      background:'#1e222b',color:'#f3f4f6',border:'1px solid rgba(255,255,255,0.14)',\n"
    "      borderRadius:'10px',boxShadow:'0 16px 36px rgba(0,0,0,0.65), 0 2px 8px rgba(0,0,0,0.4)',padding:'5px 0',\n"
    "      fontFamily:'-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif',\n"
    "      fontSize:'13px',lineHeight:'1.4',userSelect:'none',boxSizing:'border-box',\n"
    "      cursor:'default'\n"
    "    });\n"
    "    var svgCopy = '<svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\"><rect x=\"8\" y=\"8\" width=\"12\" height=\"12\" fill=\"none\" stroke=\"#9aa0a6\" stroke-width=\"2\"/><path d=\"M4 16H3A1 1 0 0 1 2 15V3A1 1 0 0 1 3 2H15A1 1 0 0 1 16 3V4\" fill=\"none\" stroke=\"#9aa0a6\" stroke-width=\"2\"/></svg>';\n"
    "    var svgCut = '<svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\"><circle cx=\"6\" cy=\"6\" r=\"3\" fill=\"none\" stroke=\"#9aa0a6\" stroke-width=\"2\"/><circle cx=\"6\" cy=\"18\" r=\"3\" fill=\"none\" stroke=\"#9aa0a6\" stroke-width=\"2\"/><line x1=\"20\" y1=\"4\" x2=\"8.5\" y2=\"15.5\" stroke=\"#9aa0a6\" stroke-width=\"2\"/><line x1=\"20\" y1=\"20\" x2=\"8.5\" y2=\"8.5\" stroke=\"#9aa0a6\" stroke-width=\"2\"/></svg>';\n"
    "    var svgPaste = '<svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\"><path d=\"M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2\" fill=\"none\" stroke=\"#9aa0a6\" stroke-width=\"2\"/><rect x=\"8\" y=\"2\" width=\"8\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"#9aa0a6\" stroke-width=\"2\"/></svg>';\n"
    "    var svgReload = '<svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\"><path d=\"M23 4V10H17M1 20V14H7M3.5 9A9 9 0 0 1 18.3 5.6L23 10M1 14L5.6 18.4A9 9 0 0 0 20.5 15\" fill=\"none\" stroke=\"#9aa0a6\" stroke-width=\"2\"/></svg>';\n"
    "    var svgSelectAll = '<svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\"><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" fill=\"none\" stroke=\"#9aa0a6\" stroke-width=\"2\"/><path d=\"M8 12L11 15L16 9\" fill=\"none\" stroke=\"#9aa0a6\" stroke-width=\"2\"/></svg>';\n"
    "    var svgInspect = '<svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\"><circle cx=\"11\" cy=\"11\" r=\"8\" fill=\"none\" stroke=\"#9aa0a6\" stroke-width=\"2\"/><line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\" stroke=\"#9aa0a6\" stroke-width=\"2\"/></svg>';\n"
    "    itemCut = item(svgCut, '剪切', 'Ctrl+X', function(){ if(document.execCommand) document.execCommand('cut'); });\n"
    "    itemCopy = item(svgCopy, '复制', 'Ctrl+C', function(){\n"
    "      var selText = (window.getSelection ? window.getSelection().toString() : '');\n"
    "      if(navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(selText);\n"
    "      else if(document.execCommand) document.execCommand('copy');\n"
    "    });\n"
    "    itemPaste = item(svgPaste, '粘贴', 'Ctrl+V', function(){ if(document.execCommand) document.execCommand('paste'); });\n"
    "    sepInput = sep();\n"
    "    itemSelectAll = item(svgSelectAll, '全选', 'Ctrl+A', function(){ if(document.execCommand) document.execCommand('selectAll'); });\n"
    "    itemReload = item(svgReload, '重新加载', 'Ctrl+R', function(){ if(window.location && window.location.reload) window.location.reload(); });\n"
    "    sepDT = sep();\n"
    "    itemInspect = item(svgInspect, '检查元素', 'Inspect', function(){ if(window.__miniDT) window.__miniDT.inspect(CM.__targetNode); });\n"
    "    document.body.appendChild(CM);\n"
    "  }\n"
    "  \n"
    "  window.addEventListener('contextmenu', function(e){\n"
    "    if(document.pointerLockElement) return;\n"
    "    if(e && e.preventDefault) e.preventDefault();\n"
    "    initContextMenu();\n"
    "    CM.__targetNode = e.target;\n"
    "    var isInput = (e.target && (e.target.tagName==='INPUT' || e.target.tagName==='TEXTAREA'));\n"
    "    var selText = '';\n"
    "    if(window.getSelection){\n"
    "      try { selText = window.getSelection().toString(); } catch(err){}\n"
    "    }\n"
    "    var hasSelection = (selText && selText.trim().length > 0);\n"
    "    itemCut.style.display = isInput ? 'flex' : 'none';\n"
    "    itemCopy.style.display = (hasSelection || isInput) ? 'flex' : 'none';\n"
    "    itemPaste.style.display = isInput ? 'flex' : 'none';\n"
    "    sepInput.style.display = (isInput || hasSelection) ? 'block' : 'none';\n"
    "    var x = (e.clientX !== undefined) ? e.clientX : ((e.pageX !== undefined) ? e.pageX - (window.scrollX || 0) : (e.x || 0));\n"
    "    var y = (e.clientY !== undefined) ? e.clientY : ((e.pageY !== undefined) ? e.pageY - (window.scrollY || 0) : (e.y || 0));\n"
    "    var winW = window.innerWidth || (document.documentElement && document.documentElement.clientWidth) || 1280;\n"
    "    var winH = window.innerHeight || (document.documentElement && document.documentElement.clientHeight) || 800;\n"
    "    var menuW = 180;\n"
    "    var menuH = isInput ? 180 : (hasSelection ? 150 : 120);\n"
    "    if(x + menuW > winW) x = Math.max(8, winW - menuW - 8);\n"
    "    if(y + menuH > winH) y = Math.max(8, winH - menuH - 8);\n"
    "    if(x < 8) x = 8;\n"
    "    if(y < 8) y = 8;\n"
    "    css(CM, {display:'block',left:x+'px',top:y+'px',width:menuW+'px'});\n"
    "  });\n"
    "  \n"
    "  /* 全局防残留关闭机制：监听 mousedown/click/scroll/blur/Escape */\n"
    "  function onDismiss(e){\n"
    "    if(!CM || CM.style.display === 'none') return;\n"
    "    var cur = e.target;\n"
    "    while(cur){\n"
    "      if(cur === CM) return;\n"
    "      cur = cur.parentNode;\n"
    "    }\n"
    "    closeContextMenu();\n"
    "  }\n"
    "  window.addEventListener('mousedown', onDismiss);\n"
    "  window.addEventListener('click', onDismiss);\n"
    "  window.addEventListener('scroll', closeContextMenu);\n"
    "  window.addEventListener('blur', closeContextMenu);\n"
    "  window.addEventListener('keydown', function(e){\n"
    "    if(e.key==='Escape'||e.keyCode===27) closeContextMenu();\n"
    "  });\n"
    "  initContextMenu();\n"
    "})();\n";

int mini_devtools_install(struct MiniBridge *b)
{
    if (!b)
        return 1;
    return mini_bridge_eval(b, DEVTOOLS_JS, strlen(DEVTOOLS_JS), "<devtools>");
}

int mini_devtools_toggle(struct MiniBridge *b)
{
    if (!b)
        return 1;

    char buf[128];
    snprintf(buf, sizeof buf, "window.__miniDT && window.__miniDT.toggle && window.__miniDT.toggle()");
    char out[128];

    if (mini_bridge_eval_to_json(b, buf, out, sizeof out) != 0)
    {
        fprintf(stderr, "\033[31m[DevTools] 面板调起失败，JS 引擎抛出异常: %s\033[0m\n", out);
    }
    return 0;
}